export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';

export const FILE_NLP_REQUEST = 'FILE_NLP_REQUEST';
export const FILE_NLP_SUCCESS = 'FILE_NLP_SUCCESS';
export const FILE_NLP_FAILED = 'FILE_NLP_FAILED';