export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";

export const USER_AUTH_REHYDRATE = "USER_AUTH_REHYDRATE";
export const USER_AUTH_RESET = "USER_AUTH_RESET";

export const USER_AUTH_LOGOUT = "USER_AUTH_LOGOUT";

export const USER_UPLOAD_REQUEST = "USER_UPLOAD_REQUEST";
export const USER_UPLOAD_SUCCESS = "USER_UPLOAD_SUCCESS";
export const USER_UPLOAD_FAIL = "USER_UPLOAD_FAIL";
