export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";

export const USER_AUTH_REHYDRATE = "USER_AUTH_REHYDRATE";
export const USER_AUTH_RESET = "USER_AUTH_RESET";
